project_id = "qmzccajkllfdisnzhjjw"

[functions.analyze-pdf]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.generate-document]
verify_jwt = false

[functions.summarize-contract]
verify_jwt = false

[functions.reset-monthly-credits]
verify_jwt = false
